const express = require('express');
const router = express.Router();
const UserController = require('../controller/user.controller');
router.post("/register", UserController.register);
router.post("/forgot-password", UserController.forgotPassword);
router.post("/reset-password/:token", UserController.resetPassword);
router.post('/login', UserController.loginWithMobile);
router.post('/exam-history', UserController.submitExamResults);
router.get('/exam-history/:userId/:examAttemptId', UserController.getExamReviewDetails);
router.get('/profile/mobile/:mobile', UserController.getUserByMobile);
router.get("/profile/:id", UserController.getUserProfile);
router.put("/update/:id", UserController.updateProfile);
router.delete("/delete/:id", UserController.deleteUser);
module.exports = router;